---
- name: Configure tomcat
  hosts: all
  tasks:
    - name: Install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: Install tomcat10-admin
      apt: 
        name: tomcat10-admin
        state: present
    - name: Copy customised tomcat-users
      copy:
       src: tomcat-users.xml
       dest: /etc/tomcat10
    - name: Change port
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: Restart tomcat10
      service: 
        name: tomcat10
        state: restarted
    - name: pause for 50 secns
      pause:
        seconds: 50
    - name: Check tomcat on server1
      uri:
        url: http://172.31.12.224:9090
        status_code: 200
    - name: Check tomcat on server2
      uri:
        url: http://172.31.14.9:9090
        status_code: 200
...


