---
- name: Create users and copy files into home dirs
  hosts: all
  tasks:
    - name: Create multiple users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: amma, b: Apple, c: /tmp/amma} 
        - {a: nanna, b: Apple, c: /tmp/nanna}

    - name: copy files into users home dirs
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd, b: /tmp/amma}
        - {a: /etc/group, b: /home/nanna}
...
