---
- name: Create an empty folder and Download jenkins.war into it
  hosts: all
  tasks:
    - name: Create an emty folder
      file:
        name: /tmp/dri1
        state: directory
    - name: Download jenkins.war
      get_url: 
        url: https://get.jenkins.io/war-stable/2.541.1/jenkins.war
        dest: /tmp/dri1
    - name: Change premissions of jenkins.war
      file:
        name: /tmp/dri1/jenkins.war
        mode: 750
        owner: root
        group: root
...
